# Generated by Django 3.1.5 on 2021-03-19 08:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
                'ordering': ('tree_id', 'level'),
            },
        ),
        migrations.CreateModel(
            name='ECB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='core.category')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название параметра')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='FieldTransistor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Название')),
                ('voltage_ds', models.IntegerField(null=True, verbose_name='Макс. напряжение сток-исток')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.case', verbose_name='Корпус')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementTyper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', mptt.fields.TreeOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('parameters', models.ManyToManyField(null=True, to='core.Parameters')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
        migrations.CreateModel(
            name='ElementSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Значение параметра')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ecb', verbose_name='Элемент')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parameters', verbose_name='Наименование параметра')),
            ],
            options={
                'verbose_name': 'Значение элемента',
                'verbose_name_plural': 'Значения элементов',
            },
        ),
        migrations.AddField(
            model_name='ecb',
            name='typer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elementtyper'),
        ),
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Название')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.case', verbose_name='Корпус')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer', verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='BipolarTransistor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Название')),
                ('voltage_ce', models.FloatField(null=True, verbose_name='Макс. напр. к-э при заданном токе к и разомкнутой цепи б.(Uкэо макс),В')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.case', verbose_name='Корпус')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
