# Generated by Django 3.1.5 on 2021-03-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementspecification',
            name='element',
        ),
        migrations.RemoveField(
            model_name='elementspecification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='elementtyper',
            name='category',
        ),
        migrations.RemoveField(
            model_name='elementtyper',
            name='parameters',
        ),
        migrations.DeleteModel(
            name='ECB',
        ),
        migrations.DeleteModel(
            name='ElementSpecification',
        ),
        migrations.DeleteModel(
            name='ElementTyper',
        ),
        migrations.DeleteModel(
            name='Parameters',
        ),
    ]
