# Generated by Django 3.1.5 on 2021-03-19 08:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210319_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='core.category')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название параметра')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='ElementTyper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', mptt.fields.TreeOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('parameters', models.ManyToManyField(null=True, to='core.Parameters')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
        migrations.CreateModel(
            name='ElementSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Значение параметра')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ecb', verbose_name='Элемент')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parameters', verbose_name='Наименование параметра')),
            ],
            options={
                'verbose_name': 'Значение элемента',
                'verbose_name_plural': 'Значения элементов',
            },
        ),
        migrations.AddField(
            model_name='ecb',
            name='typer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elementtyper'),
        ),
    ]
