# Generated by Django 3.1.5 on 2021-03-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210319_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecb',
            name='category',
        ),
    ]
