# Generated by Django 3.1.5 on 2021-03-19 09:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ecb_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecb',
            name='typer',
        ),
        migrations.AddField(
            model_name='category',
            name='parameters',
            field=models.ManyToManyField(null=True, to='core.Parameters'),
        ),
        migrations.AddField(
            model_name='ecb',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='core.category'),
        ),
        migrations.DeleteModel(
            name='ElementTyper',
        ),
    ]
