# Generated by Django 3.1.5 on 2021-03-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210319_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='core.Parameters'),
        ),
    ]
