# Generated by Django 3.1.5 on 2021-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210319_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementspecification',
            name='value',
            field=models.FloatField(verbose_name='Значение параметра'),
        ),
    ]
