# Generated by Django 3.1.5 on 2021-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210319_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementspecification',
            name='value',
        ),
        migrations.AddField(
            model_name='elementspecification',
            name='float_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Дробное значение'),
        ),
        migrations.AddField(
            model_name='elementspecification',
            name='int_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Целочисленное значение'),
        ),
    ]
