# Generated by Django 3.1.5 on 2021-03-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210319_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ECB',
            new_name='Element',
        ),
        migrations.RenameModel(
            old_name='ElementSpecification',
            new_name='ElementValue',
        ),
        migrations.RemoveField(
            model_name='capacitor',
            name='case',
        ),
        migrations.RemoveField(
            model_name='capacitor',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='fieldtransistor',
            name='case',
        ),
        migrations.RemoveField(
            model_name='fieldtransistor',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='BipolarTransistor',
        ),
        migrations.DeleteModel(
            name='Capacitor',
        ),
        migrations.DeleteModel(
            name='FieldTransistor',
        ),
    ]
