# Generated by Django 3.1.5 on 2021-03-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210325_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.AlterModelOptions(
            name='parametervalues',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelTable(
            name='element',
            table='element',
        ),
        migrations.AlterModelTable(
            name='elementvalue',
            table='element_value',
        ),
        migrations.AlterModelTable(
            name='parameters',
            table='parameters',
        ),
        migrations.AlterModelTable(
            name='parametervalues',
            table='parameter_values',
        ),
    ]
