# Generated by Django 3.1.5 on 2021-03-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210325_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalues',
            options={'verbose_name': 'Значение параметра', 'verbose_name_plural': 'Значения параметров'},
        ),
        migrations.RemoveField(
            model_name='elementvalue',
            name='float_value',
        ),
        migrations.RemoveField(
            model_name='elementvalue',
            name='int_value',
        ),
        migrations.AddField(
            model_name='elementvalue',
            name='value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.parametervalues', verbose_name='Значение параметра'),
            preserve_default=False,
        ),
    ]
