# Generated by Django 3.1.5 on 2021-03-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210325_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumParameterUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название единицы измерения параметра')),
                ('multiplier', models.IntegerField(verbose_name='Множитель единицы измерения параметра')),
            ],
            options={
                'verbose_name': 'Значение числового параметра',
                'verbose_name_plural': 'Значения числовых параметров',
                'db_table': 'num_parameter_values',
            },
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Выборочной параметр', 'verbose_name_plural': 'Выборочные параметры'},
        ),
        migrations.AlterModelOptions(
            name='parametervalues',
            options={'verbose_name': 'Значение выоборочного параметра', 'verbose_name_plural': 'Значения выборочных параметров'},
        ),
        migrations.AlterField(
            model_name='elementvalue',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parametervalues', verbose_name='Значение параметра'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='values',
            field=models.ManyToManyField(blank=True, to='core.ParameterValues', verbose_name='Возможные значения параметров'),
        ),
        migrations.CreateModel(
            name='NumParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название параметра')),
                ('units', models.ManyToManyField(blank=True, to='core.NumParameterUnits', verbose_name='Возможные значения параметров')),
            ],
            options={
                'verbose_name': 'Числовой параметр',
                'verbose_name_plural': 'Числовые параметры',
                'db_table': 'num_parameters',
            },
        ),
    ]
