# Generated by Django 3.1.5 on 2021-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210325_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementvalue',
            name='num_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Числовое значение параметра'),
        ),
    ]
