# Generated by Django 3.1.5 on 2021-03-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_elementvalue_num_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementvalue',
            name='num_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Числовое значение параметра'),
        ),
        migrations.AlterField(
            model_name='numparameters',
            name='units',
            field=models.ManyToManyField(blank=True, to='core.NumParameterUnits', verbose_name='Возможные единицы измерения параметра'),
        ),
    ]
