# Generated by Django 3.1.5 on 2021-03-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210326_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numparameterunits',
            name='multiplier',
            field=models.FloatField(verbose_name='Множитель единицы измерения параметра'),
        ),
    ]
