# Generated by Django 3.1.5 on 2021-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210326_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_parameters',
            field=models.ManyToManyField(blank=True, to='core.NumParameters', verbose_name='Числовые параметры'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='core.Parameters', verbose_name='Выборочные параметры'),
        ),
    ]
