# Generated by Django 3.1.5 on 2021-03-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210326_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementvalue',
            name='num_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.numparameters', verbose_name='Наименование числового параметра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementvalue',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parameters', verbose_name='Наименование выборочного параметра'),
        ),
        migrations.AlterField(
            model_name='elementvalue',
            name='num_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение числового параметра'),
        ),
        migrations.AlterField(
            model_name='elementvalue',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parametervalues', verbose_name='Значение выборочного параметра'),
        ),
    ]
