# Generated by Django 3.1.5 on 2021-03-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210326_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementvalue',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parameters', verbose_name='Наименование выборочного параметра'),
        ),
        migrations.AlterField(
            model_name='elementvalue',
            name='num_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.numparameters', verbose_name='Наименование числового параметра'),
        ),
    ]
