# Generated by Django 3.1.5 on 2021-03-30 05:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210326_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numparameters',
            options={'verbose_name': 'Единица измерения параметра', 'verbose_name_plural': 'Единицы измерения параметров'},
        ),
        migrations.AddField(
            model_name='category',
            name='my_file',
            field=models.FileField(blank=True, upload_to='my_file'),
        ),
        migrations.AlterField(
            model_name='element',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='core.category', verbose_name='Категория'),
        ),
    ]
