# Generated by Django 3.1.5 on 2021-03-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210330_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='my_file',
        ),
    ]
