# Generated by Django 3.1.5 on 2021-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_category_my_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numparameters',
            options={'verbose_name': 'Числовой параметр', 'verbose_name_plural': 'Числовые параметры'},
        ),
        migrations.AlterModelOptions(
            name='numparameterunits',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.CreateModel(
            name='ComplexParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название сложного параметра')),
                ('num_parameters', models.ManyToManyField(blank=True, to='core.NumParameters', verbose_name='Числовые поля')),
                ('parameters', models.ManyToManyField(blank=True, to='core.Parameters', verbose_name='Выборочные поля')),
            ],
        ),
    ]
