# Generated by Django 3.1.5 on 2021-04-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210409_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexparameters',
            options={'verbose_name': 'Сложный параметр', 'verbose_name_plural': 'Сложные параметры'},
        ),
        migrations.AlterModelTable(
            name='complexparameters',
            table='complex_parameters',
        ),
    ]
