# Generated by Django 3.1.5 on 2021-05-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210409_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexparameters',
            name='num_parameters',
        ),
        migrations.RemoveField(
            model_name='complexparameters',
            name='parameters',
        ),
    ]
