# Generated by Django 3.1.5 on 2021-05-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210504_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementvalue',
            old_name='num_name',
            new_name='num_param_name',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='num_value',
            new_name='num_param_value',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='name',
            new_name='param_name',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='value',
            new_name='param_value',
        ),
    ]
