# Generated by Django 3.1.5 on 2021-05-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210506_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementvalue',
            old_name='num_param_name',
            new_name='num_param',
        ),
        migrations.RenameField(
            model_name='elementvalue',
            old_name='param_name',
            new_name='param',
        ),
    ]
