# Generated by Django 3.1.5 on 2021-05-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210506_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=60)),
                ('element_manufacturer', models.CharField(max_length=60)),
                ('element_power', models.IntegerField()),
            ],
            options={
                'db_table': 'full_elements',
            },
        ),
    ]
