# Generated by Django 3.1.5 on 2021-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fullelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
