# Generated by Django 3.1.5 on 2021-05-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_element_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='description',
        ),
    ]
