# Generated by Django 3.1.5 on 2021-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_category_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='elementvalue',
            index=models.Index(fields=['id', 'num_param_value'], name='element_val_id_b92c04_idx'),
        ),
    ]
