# Generated by Django 3.1.5 on 2021-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210522_1243'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='elementvalue',
            name='element_val_num_par_66e56d_idx',
        ),
        migrations.AddIndex(
            model_name='elementvalue',
            index=models.Index(fields=['num_param_value', 'num_param'], name='element_val_num_par_e4926e_idx'),
        ),
    ]
