# Generated by Django 3.1.5 on 2021-05-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210522_1246'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='elementvalue',
            name='element_val_num_par_e4926e_idx',
        ),
    ]
