# Generated by Django 3.1.5 on 2021-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210522_1251'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parametervalues',
            name='parameter_v_name_a6f205_idx',
        ),
        migrations.AlterField(
            model_name='parametervalues',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
