# Generated by Django 3.1.5 on 2021-05-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210522_1256'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parametervalues',
            name='parameter_v_name_a6f205_idx',
        ),
        migrations.AlterField(
            model_name='parametervalues',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
