# Generated by Django 3.1.5 on 2021-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210522_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalues',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='parametervalues',
            index=models.Index(fields=['name', 'id'], name='parameter_v_name_a6f205_idx'),
        ),
    ]
