# Generated by Django 3.1.5 on 2021-05-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210527_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='elementvalue',
            name='param_value_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Значение выборочного параметра'),
        ),
        migrations.AlterField(
            model_name='elementvalue',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parametervalues', verbose_name='Номер выборочного параметра'),
        ),
    ]
