# Generated by Django 3.1.5 on 2021-06-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210527_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementvalue',
            name='param_value_name',
        ),
    ]
